local network = require(game.ReplicatedStorage.modules.network)
local teleportServer = require(game.ReplicatedStorage.modules.teleportServer)
network.event("loadCharacterSlot", function(player, characterSlotId)
    print("Load: character data")
    local lastPlace = teleportServer.getCurrentPlace(player)
    teleportServer.teleportPlayer(player, lastPlace, {})
end)
