local updateXpBar = game.ReplicatedStorage.events:WaitForChild("updateXpBar")
local gui = require(game.ReplicatedStorage.modules.client.gui)
local makeChatMessage = game.ReplicatedStorage.events:WaitForChild("makeChatMessage")
updateXpBar.OnClientEvent:Connect(function(xp, currentLevel)
    gui.setXpBarData(currentLevel, xp)
end)
makeChatMessage.OnClientEvent:Connect(function(message, textColor, textSize)
    gui.printChatMessage(message, textColor, textSize)
end)