local playersService = game:GetService("Players")
local playerModule = require(game.ReplicatedStorage:WaitForChild("modules").player)
playersService.PlayerAdded:Connect(function(player)
    playerModule.playerAdded(player)
end)